export const emailStrings = {
  en: {
    purchaseConfirmation: {
      subject: {
        pro: "Welcome to EnergyForge PRO 🎉",
        coach: "Welcome to EnergyForge Coach 🎉",
      },
      preheader: "Your purchase is confirmed — your personal energy plan is generating now.",
      greeting: "Hi there 👋",
      heading: {
        pro: "Welcome to EnergyForge PRO",
        coach: "Welcome to EnergyForge Coach",
      },
      intro: "Your purchase is confirmed. Your personalized energy diagnostic plan is being generated right now — it usually takes about 30 seconds.",
      whatsNext: "What happens next",
      step1: "Open your plan in the dashboard and wait ~30 seconds for it to finish generating",
      step2: "Once ready, you'll find your full 30-day energy protocol with morning routine, supplements, and recovery strategy",
      step3: "Save this email — it's your direct access link",
      ctaButton: "Open my plan",
      questions: "Questions? Contact us at",
      supportEmail: "support@energyforge.app",
      footerTagline: "AI-powered personal energy diagnostics",
      footerLinks: { refund: "Refund Policy", terms: "Terms", privacy: "Privacy" },
      footerCopyright: "© 2026 EnergyForge · Prague, Czech Republic",
    },
    planReady: {
      subject: "Your energy plan is ready ⚡",
      preheader: "Your personalized 30-day energy protocol is generated and waiting.",
      greeting: "Hi there 👋",
      heading: "Your energy plan is ready ⚡",
      phenotypeIntro: "We've pinpointed your energy type: {name}.",
      intro: "Your personalized 30-day energy diagnostic protocol is ready. Here's a quick preview of what's inside:",
      previewLabel: "Your summary:",
      whatsInside: "Inside your plan",
      bullet1: "⚡ Morning Protocol — circadian-aligned wake routine",
      bullet2: "⚡ Afternoon Recovery — crash-prevention strategy",
      bullet3: "⚡ Sleep Architecture — quality optimization tactics",
      bullet4: "⚡ Personalized Supplements — exact dosages for your profile",
      ctaButton: "Open my plan",
      saveTip: "💡 Save this email for quick access later.",
      questions: "Questions? Contact us at",
      supportEmail: "support@energyforge.app",
      footerTagline: "AI-powered personal energy diagnostics",
      footerLinks: { refund: "Refund Policy", terms: "Terms", privacy: "Privacy" },
      footerCopyright: "© 2026 EnergyForge · Prague, Czech Republic",
    },
  },
  ru: {
    purchaseConfirmation: {
      subject: {
        pro: "Добро пожаловать в EnergyForge PRO 🎉",
        coach: "Добро пожаловать в EnergyForge Coach 🎉",
      },
      preheader: "Покупка подтверждена — ваш персональный план генерируется прямо сейчас.",
      greeting: "Привет 👋",
      heading: {
        pro: "Добро пожаловать в EnergyForge PRO",
        coach: "Добро пожаловать в EnergyForge Coach",
      },
      intro: "Покупка подтверждена. Ваш персональный план энергетической диагностики генерируется прямо сейчас — это занимает около 30 секунд.",
      whatsNext: "Что дальше",
      step1: "Откройте план в дашборде и подождите ~30 секунд пока он догенерируется",
      step2: "После готовности вы получите полный 30-дневный протокол: утренние ритуалы, добавки и стратегию восстановления",
      step3: "Сохраните это письмо — это ваша прямая ссылка для доступа",
      ctaButton: "Открыть мой план",
      questions: "Вопросы? Напишите нам на",
      supportEmail: "support@energyforge.app",
      footerTagline: "AI-платформа персональной энергетической диагностики",
      footerLinks: { refund: "Возврат средств", terms: "Условия", privacy: "Конфиденциальность" },
      footerCopyright: "© 2026 EnergyForge · Прага, Чехия",
    },
    planReady: {
      subject: "Ваш план энергии готов ⚡",
      preheader: "Персональный 30-дневный протокол сгенерирован и ждёт вас.",
      greeting: "Привет 👋",
      heading: "Ваш план энергии готов ⚡",
      phenotypeIntro: "Мы определили ваш энергетический тип: {name}.",
      intro: "Персональный 30-дневный протокол энергетической диагностики готов. Вот краткое превью того, что внутри:",
      previewLabel: "Ваш обзор:",
      whatsInside: "Что внутри плана",
      bullet1: "⚡ Утренний протокол — пробуждение по циркадным ритмам",
      bullet2: "⚡ Дневное восстановление — стратегия против упадка сил",
      bullet3: "⚡ Архитектура сна — оптимизация качества сна",
      bullet4: "⚡ Персональные добавки — точные дозировки под ваш профиль",
      ctaButton: "Открыть мой план",
      saveTip: "💡 Сохраните это письмо для быстрого доступа.",
      questions: "Вопросы? Напишите нам на",
      supportEmail: "support@energyforge.app",
      footerTagline: "AI-платформа персональной энергетической диагностики",
      footerLinks: { refund: "Возврат средств", terms: "Условия", privacy: "Конфиденциальность" },
      footerCopyright: "© 2026 EnergyForge · Прага, Чехия",
    },
  },
} as const;

export type EmailStringsKey = keyof typeof emailStrings.en;
