export const emailStrings = {
  en: {
    purchaseConfirmation: {
      subject: {
        pro: "Welcome to EnergyForge PRO 🎉",
        coach: "Welcome to EnergyForge Coach 🎉",
      },
      preheader: "Your purchase is confirmed — your personal energy plan is generating now.",
      greeting: "Hi there 👋",
      heading: {
        pro: "Welcome to EnergyForge PRO",
        coach: "Welcome to EnergyForge Coach",
      },
      intro: "Your purchase is confirmed. Your personalized energy diagnostic plan is being generated right now — it usually takes about 30 seconds.",
      whatsNext: "What happens next",
      step1: "Open your plan in the dashboard and wait ~30 seconds for it to finish generating",
      step2: "Once ready, you'll find your full 30-day energy protocol with morning routine, supplements, and recovery strategy",
      step3: "Save this email — it's your direct access link",
      ctaButton: "Open my plan",
      questions: "Questions? Contact us at",
      supportEmail: "support@energyforge.app",
      footerTagline: "AI-powered personal energy diagnostics",
      footerLinks: { refund: "Refund Policy", terms: "Terms", privacy: "Privacy" },
      footerCopyright: "© 2026 EnergyForge · Prague, Czech Republic",
    },
    planReady: {
      subject: "Your energy plan is ready ⚡",
      preheader: "Your personalized 30-day energy protocol is generated and waiting.",
      greeting: "Hi there 👋",
      heading: "Your energy plan is ready ⚡",
      phenotypeIntro: "We've pinpointed your energy type: {name}.",
      intro: "Your personalized 30-day energy diagnostic protocol is ready. Here's a quick preview of what's inside:",
      previewLabel: "Your summary:",
      whatsInside: "Inside your plan",
      bullet1: "⚡ Morning Protocol — circadian-aligned wake routine",
      bullet2: "⚡ Afternoon Recovery — crash-prevention strategy",
      bullet3: "⚡ Sleep Architecture — quality optimization tactics",
      bullet4: "⚡ Personalized Supplements — exact dosages for your profile",
      ctaButton: "Open my plan",
      saveTip: "💡 Save this email for quick access later.",
      questions: "Questions? Contact us at",
      supportEmail: "support@energyforge.app",
      footerTagline: "AI-powered personal energy diagnostics",
      footerLinks: { refund: "Refund Policy", terms: "Terms", privacy: "Privacy" },
      footerCopyright: "© 2026 EnergyForge · Prague, Czech Republic",
    },
  },
  cs: {
    purchaseConfirmation: {
      subject: {
        pro: "Vítej v EnergyForge PRO 🎉",
        coach: "Vítej v EnergyForge Coach 🎉",
      },
      preheader: "Nákup je potvrzený — tvůj osobní energetický plán se právě generuje.",
      greeting: "Ahoj 👋",
      heading: {
        pro: "Vítej v EnergyForge PRO",
        coach: "Vítej v EnergyForge Coach",
      },
      intro: "Tvůj nákup je potvrzený. Tvůj energetický diagnostický plán na míru se právě generuje — obvykle to zabere kolem 30 sekund.",
      whatsNext: "Co bude dál",
      step1: "Otevři si plán v přehledu a počkej ~30 sekund, než se dogeneruje",
      step2: "Jakmile bude hotový, najdeš v něm celý 30denní energetický protokol s ranní rutinou, doplňky a strategií regenerace",
      step3: "Tenhle e-mail si nech — je to tvůj přímý přístupový odkaz",
      ctaButton: "Otevřít můj plán",
      questions: "Máš otázky? Napiš nám na",
      supportEmail: "support@energyforge.app",
      footerTagline: "Osobní energetická diagnostika poháněná AI",
      footerLinks: { refund: "Podmínky vrácení peněz", terms: "Obchodní podmínky", privacy: "Ochrana soukromí" },
      footerCopyright: "© 2026 EnergyForge · Praha, Česká republika",
    },
    planReady: {
      subject: "Tvůj energetický plán je hotový ⚡",
      preheader: "Tvůj 30denní energetický protokol na míru je vygenerovaný a čeká na tebe.",
      greeting: "Ahoj 👋",
      heading: "Tvůj energetický plán je hotový ⚡",
      phenotypeIntro: "Určili jsme tvůj energetický typ: {name}.",
      intro: "Tvůj 30denní energetický diagnostický protokol na míru je hotový. Tady je rychlá ochutnávka toho, co je uvnitř:",
      previewLabel: "Tvoje shrnutí:",
      whatsInside: "Co najdeš v plánu",
      bullet1: "⚡ Ranní protokol — probouzení sladěné s cirkadiánním rytmem",
      bullet2: "⚡ Odpolední regenerace — strategie proti propadu",
      bullet3: "⚡ Architektura spánku — taktiky pro lepší kvalitu spánku",
      bullet4: "⚡ Doplňky na míru — přesné dávkování pro tvůj profil",
      ctaButton: "Otevřít můj plán",
      saveTip: "💡 Tenhle e-mail si ulož pro rychlý přístup.",
      questions: "Máš otázky? Napiš nám na",
      supportEmail: "support@energyforge.app",
      footerTagline: "Osobní energetická diagnostika poháněná AI",
      footerLinks: { refund: "Podmínky vrácení peněz", terms: "Obchodní podmínky", privacy: "Ochrana soukromí" },
      footerCopyright: "© 2026 EnergyForge · Praha, Česká republika",
    },
  },
} as const;

export type EmailStringsKey = keyof typeof emailStrings.en;
