"use client";

import Link from "next/link";
import { useI18n } from "@/lib/i18n-context";
import { t, pick } from "@/lib/translations";
import LegalLayout from "@/components/LegalLayout";
import { Mail, Ext } from "@/components/LegalHelpers";
import { COMPANY } from "@/lib/company";

// Chrome (navbar, title, footer) follows the URL language via
// RouteLangProvider in the [lang] layout. The document BODY stays English on
// both variants until the reviewed Czech legal text is ready (native review
// pending) — swap <TermsEN /> for a lang switch here when it lands.
export default function TermsContent() {
  const { lang } = useI18n();
  return (
    <LegalLayout title={pick(t.legal.termsTitle, lang)} lastUpdated="August 27, 2026">
      <TermsEN />
    </LegalLayout>
  );
}

function TermsEN() {
  return (
    <>
      <h2>1. Seller</h2>
      <p>
        EnergyForge (energyforge.app) is operated by{" "}
        <strong>{COMPANY.name}</strong>, a company registered in the Czech
        Republic, ID No. (IČO) {COMPANY.ico}, VAT No. {COMPANY.dic},
        registered office: {COMPANY.addressEn}, {COMPANY.registrationEn} (the
        &ldquo;Seller&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;).
      </p>

      <h2>2. Agreement to Terms</h2>
      <p>
        By accessing or using energyforge.app (&ldquo;Service&rdquo;), you
        agree to be bound by these Terms of Service (&ldquo;Terms&rdquo;). If
        you do not agree, please do not use the Service.
      </p>

      <h2>3. Description of Service</h2>
      <p>
        EnergyForge is an AI-powered personal energy diagnostic platform.
        Based on your answers to a 10-question questionnaire, our AI (powered
        by Anthropic Claude) generates a personalized 30-day plan covering:
      </p>
      <ul>
        <li>Sleep optimization</li>
        <li>Supplement recommendations</li>
        <li>Stress management</li>
        <li>Nutrition guidance</li>
      </ul>

      <h2 id="medical-disclaimer">4. ⚠️ Medical Disclaimer — IMPORTANT</h2>
      <div className="legal-warning">
        <p>
          <strong>
            EnergyForge is a wellness and lifestyle platform.
          </strong>{" "}
          It is <strong>NOT a medical service</strong> and is{" "}
          <strong>
            NOT a substitute for professional medical advice, diagnosis, or
            treatment
          </strong>
          .
        </p>
        <p>
          The personalized plans, supplement recommendations, nutrition
          suggestions, and lifestyle guidance provided by EnergyForge are
          generated by AI based on self-reported quiz responses and are for{" "}
          <strong>informational and educational purposes only</strong>.
        </p>
        <p>
          <strong>
            Always consult a qualified healthcare professional
          </strong>{" "}
          (doctor, registered dietitian, pharmacist) BEFORE:
        </p>
        <ul>
          <li>Starting any new supplement regimen</li>
          <li>Making significant changes to your diet</li>
          <li>Starting a new exercise program</li>
          <li>
            Acting on any recommendation if you have any pre-existing
            medical condition, are pregnant or breastfeeding, are taking
            prescription medications, or are under 18
          </li>
        </ul>
        <p>
          <strong>
            Do not disregard, avoid, or delay seeking professional medical
            advice
          </strong>{" "}
          because of information provided by EnergyForge.
        </p>
        <p>
          In case of a medical emergency, call your local emergency number
          immediately.
        </p>
        <p>
          EnergyForge, its founders, and affiliates are{" "}
          <strong>
            not liable for any adverse effects, health consequences, or
            damages
          </strong>{" "}
          resulting from following AI-generated recommendations without
          proper medical consultation.
        </p>
        <p>
          Supplements mentioned in plans are{" "}
          <strong>
            not evaluated by the FDA, EMA, or any other regulatory
            authority
          </strong>{" "}
          for the specific uses suggested. They are not intended to
          diagnose, treat, cure, or prevent any disease.
        </p>
      </div>

      <h2>5. Eligibility</h2>
      <p>
        You must be <strong>at least 18 years old</strong> to use this
        Service. By using the Service, you confirm that you meet this age
        requirement.
      </p>

      <h2>6. Pricing and Payments</h2>
      <p>
        <strong>Plans:</strong>
      </p>
      <ul>
        <li>
          <strong>Starter</strong> — Free (limited features)
        </li>
        <li>
          <strong>PRO</strong> — €9.99 one-time payment
        </li>
      </ul>
      <p>
        <strong>Payment terms:</strong>
      </p>
      <ul>
        <li>All payments are processed securely through Stripe</li>
        <li>Prices are in Euros (€) and include applicable VAT</li>
        <li>PRO is a one-time payment — nothing renews and nothing to cancel</li>
      </ul>

      <h2>7. Refund Policy</h2>
      <p>
        <strong>
          EU consumers have a 14-day right of withdrawal
        </strong>{" "}
        under EU Consumer Rights Directive, subject to the following:
      </p>
      <ul>
        <li>
          You may request a refund within 14 days of purchase if you have{" "}
          <strong>not yet accessed</strong> your personalized plan.
        </li>
        <li>
          <strong>
            Once you access and view your AI-generated plan, the right of
            withdrawal is waived
          </strong>{" "}
          (as per EU law Article 16(m) — digital content delivered
          immediately after purchase, with your explicit consent).
        </li>
      </ul>
      <p>
        <strong>To request a refund:</strong> email <Mail /> with your order
        details.
      </p>
      <p>
        See our <Link href="/refund-policy">Refund Policy</Link> for full
        details.
      </p>

      <h2>8. User Responsibilities</h2>
      <p>You agree to:</p>
      <ul>
        <li>Provide accurate and truthful information in the questionnaire</li>
        <li>Use the Service only for personal, non-commercial purposes</li>
        <li>Not share, resell, or redistribute AI-generated plans</li>
        <li>Not attempt to reverse-engineer or hack the Service</li>
        <li>Not use the Service for any illegal purpose</li>
      </ul>

      <h2>9. Intellectual Property</h2>
      <p>
        All content on EnergyForge, including but not limited to the website
        design, logo, text, graphics, and AI-generated plans (in their
        formatted presentation), is the property of EnergyForge or its
        licensors and is protected by copyright and other intellectual
        property laws.
      </p>
      <p>
        You receive a{" "}
        <strong>personal, non-transferable license</strong> to use your
        generated plan for your own personal use only.
      </p>

      <h2>10. AI-Generated Content Disclaimer</h2>
      <p>
        Plans generated by our Service are produced by AI (Anthropic Claude)
        based on your input. While we strive for accuracy:
      </p>
      <ul>
        <li>
          AI recommendations may contain errors or outdated information
        </li>
        <li>Individual results may vary significantly</li>
        <li>No guarantee of specific health, energy, or wellness outcomes</li>
        <li>You use AI-generated recommendations at your own risk</li>
      </ul>

      <h2>11. Prohibited Uses</h2>
      <p>You may not:</p>
      <ul>
        <li>Use the Service if you are under 18</li>
        <li>Impersonate others or provide false information</li>
        <li>Use automated systems (bots, scrapers) to access the Service</li>
        <li>Attempt to disrupt or overload the Service</li>
        <li>Use the Service to harm yourself or others</li>
      </ul>

      <h2>12. Service Availability</h2>
      <p>
        We strive to keep the Service available 24/7, but we do not guarantee
        uninterrupted access. We may suspend or modify the Service for
        maintenance, updates, or other reasons without prior notice.
      </p>

      <h2>13. Limitation of Liability</h2>
      <p>To the fullest extent permitted by law:</p>
      <ul>
        <li>
          EnergyForge is not liable for any indirect, incidental, or
          consequential damages
        </li>
        <li>
          Our total liability is limited to the amount you paid us in the
          last 12 months
        </li>
        <li>
          We are not liable for health outcomes or decisions made based on
          AI-generated recommendations
        </li>
      </ul>

      <h2>14. Termination</h2>
      <p>
        We may terminate or suspend your access to the Service at any time,
        without prior notice, for violation of these Terms.
      </p>

      <h2>15. Governing Law</h2>
      <p>
        These Terms are governed by the laws of the European Union and the
        country of our establishment, without regard to conflict of law
        principles.
      </p>
      <p>
        Any disputes will be resolved in the competent courts of our
        jurisdiction, or through EU&apos;s Online Dispute Resolution
        platform:{" "}
        <Ext href="https://ec.europa.eu/consumers/odr/">
          https://ec.europa.eu/consumers/odr/
        </Ext>
      </p>

      <h2>16. Changes to Terms</h2>
      <p>
        We reserve the right to modify these Terms at any time. Changes will
        be effective upon posting. Continued use of the Service constitutes
        acceptance of the updated Terms.
      </p>

      <h2>17. Contact</h2>
      <p>
        For any questions about these Terms: <Mail />
      </p>
    </>
  );
}
