"use client";

import { useI18n } from "@/lib/i18n-context";
import { t, pick } from "@/lib/translations";
import LegalLayout from "@/components/LegalLayout";
import { Mail, Ext } from "@/components/LegalHelpers";

export default function TermsPage() {
  const { lang } = useI18n();
  const lastUpdated = lang === "ru" ? "20 апреля 2026" : "April 20, 2026";

  return (
    <LegalLayout
      title={pick(t.legal.termsTitle, lang)}
      lastUpdated={lastUpdated}
    >
      {lang === "ru" ? <TermsRU /> : <TermsEN />}
    </LegalLayout>
  );
}

function TermsEN() {
  return (
    <>
      <h2>1. Agreement to Terms</h2>
      <p>
        By accessing or using energyforge.app (&ldquo;Service&rdquo;), you
        agree to be bound by these Terms of Service (&ldquo;Terms&rdquo;). If
        you do not agree, please do not use the Service.
      </p>

      <h2>2. Description of Service</h2>
      <p>
        EnergyForge is an AI-powered personal energy diagnostic platform.
        Based on your answers to a 9-question questionnaire, our AI (powered
        by Anthropic Claude) generates a personalized 30-day plan covering:
      </p>
      <ul>
        <li>Sleep optimization</li>
        <li>Supplement recommendations</li>
        <li>Stress management</li>
        <li>Nutrition guidance</li>
      </ul>

      <h2>3. ⚠️ Medical Disclaimer — IMPORTANT</h2>
      <div className="legal-warning">
        <p>
          <strong>EnergyForge is NOT a medical service.</strong> Our
          recommendations are for{" "}
          <strong>informational and educational purposes only</strong> and do
          not constitute medical advice, diagnosis, or treatment.
        </p>
        <ul>
          <li>
            Always consult a qualified healthcare professional before making
            changes to your diet, supplements, sleep medications, or
            lifestyle.
          </li>
          <li>
            Do not use our Service to diagnose or treat any medical condition.
          </li>
          <li>
            If you are pregnant, nursing, have a medical condition, or take
            medications, consult your doctor before following any
            recommendations.
          </li>
          <li>
            In case of medical emergency, call your local emergency services
            immediately.
          </li>
        </ul>
        <p>
          <strong>
            We are not responsible for any harm, injury, or adverse effects
          </strong>{" "}
          resulting from following recommendations generated by our Service.
        </p>
      </div>

      <h2>4. Eligibility</h2>
      <p>
        You must be <strong>at least 18 years old</strong> to use this
        Service. By using the Service, you confirm that you meet this age
        requirement.
      </p>

      <h2>5. Pricing and Payments</h2>
      <p>
        <strong>Subscription plans:</strong>
      </p>
      <ul>
        <li>
          <strong>Starter</strong> — Free (limited features)
        </li>
        <li>
          <strong>PRO</strong> — €9.99 one-time payment
        </li>
        <li>
          <strong>Coach</strong> — €24.99/month (recurring subscription)
        </li>
      </ul>
      <p>
        <strong>Payment terms:</strong>
      </p>
      <ul>
        <li>All payments are processed securely through Stripe</li>
        <li>Prices are in Euros (€) and include applicable VAT</li>
        <li>Subscriptions (Coach) auto-renew monthly until cancelled</li>
        <li>
          You can cancel your subscription at any time through your account
          settings
        </li>
      </ul>

      <h2>6. Refund Policy</h2>
      <p>
        <strong>
          EU consumers have a 14-day right of withdrawal
        </strong>{" "}
        under EU Consumer Rights Directive, subject to the following:
      </p>
      <ul>
        <li>
          You may request a refund within 14 days of purchase if you have{" "}
          <strong>not yet accessed</strong> your personalized plan.
        </li>
        <li>
          <strong>
            Once you access and view your AI-generated plan, the right of
            withdrawal is waived
          </strong>{" "}
          (as per EU law Article 16(m) — digital content delivered
          immediately after purchase, with your explicit consent).
        </li>
        <li>
          For Coach subscriptions, cancellation stops future charges but does
          not refund the current billing period.
        </li>
      </ul>
      <p>
        <strong>To request a refund:</strong> email <Mail /> with your order
        details.
      </p>

      <h2>7. User Responsibilities</h2>
      <p>You agree to:</p>
      <ul>
        <li>Provide accurate and truthful information in the questionnaire</li>
        <li>Use the Service only for personal, non-commercial purposes</li>
        <li>Not share, resell, or redistribute AI-generated plans</li>
        <li>Not attempt to reverse-engineer or hack the Service</li>
        <li>Not use the Service for any illegal purpose</li>
      </ul>

      <h2>8. Intellectual Property</h2>
      <p>
        All content on EnergyForge, including but not limited to the website
        design, logo, text, graphics, and AI-generated plans (in their
        formatted presentation), is the property of EnergyForge or its
        licensors and is protected by copyright and other intellectual
        property laws.
      </p>
      <p>
        You receive a{" "}
        <strong>personal, non-transferable license</strong> to use your
        generated plan for your own personal use only.
      </p>

      <h2>9. AI-Generated Content Disclaimer</h2>
      <p>
        Plans generated by our Service are produced by AI (Anthropic Claude)
        based on your input. While we strive for accuracy:
      </p>
      <ul>
        <li>
          AI recommendations may contain errors or outdated information
        </li>
        <li>Individual results may vary significantly</li>
        <li>No guarantee of specific health, energy, or wellness outcomes</li>
        <li>You use AI-generated recommendations at your own risk</li>
      </ul>

      <h2>10. Prohibited Uses</h2>
      <p>You may not:</p>
      <ul>
        <li>Use the Service if you are under 18</li>
        <li>Impersonate others or provide false information</li>
        <li>Use automated systems (bots, scrapers) to access the Service</li>
        <li>Attempt to disrupt or overload the Service</li>
        <li>Use the Service to harm yourself or others</li>
      </ul>

      <h2>11. Service Availability</h2>
      <p>
        We strive to keep the Service available 24/7, but we do not guarantee
        uninterrupted access. We may suspend or modify the Service for
        maintenance, updates, or other reasons without prior notice.
      </p>

      <h2>12. Limitation of Liability</h2>
      <p>To the fullest extent permitted by law:</p>
      <ul>
        <li>
          EnergyForge is not liable for any indirect, incidental, or
          consequential damages
        </li>
        <li>
          Our total liability is limited to the amount you paid us in the
          last 12 months
        </li>
        <li>
          We are not liable for health outcomes or decisions made based on
          AI-generated recommendations
        </li>
      </ul>

      <h2>13. Termination</h2>
      <p>
        We may terminate or suspend your access to the Service at any time,
        without prior notice, for violation of these Terms.
      </p>

      <h2>14. Governing Law</h2>
      <p>
        These Terms are governed by the laws of the European Union and the
        country of our establishment, without regard to conflict of law
        principles.
      </p>
      <p>
        Any disputes will be resolved in the competent courts of our
        jurisdiction, or through EU&apos;s Online Dispute Resolution
        platform:{" "}
        <Ext href="https://ec.europa.eu/consumers/odr/">
          https://ec.europa.eu/consumers/odr/
        </Ext>
      </p>

      <h2>15. Changes to Terms</h2>
      <p>
        We reserve the right to modify these Terms at any time. Changes will
        be effective upon posting. Continued use of the Service constitutes
        acceptance of the updated Terms.
      </p>

      <h2>16. Contact</h2>
      <p>
        For any questions about these Terms: <Mail />
      </p>
    </>
  );
}

function TermsRU() {
  return (
    <>
      <h2>1. Согласие с условиями</h2>
      <p>
        Используя energyforge.app (далее — «Сервис»), вы соглашаетесь с
        настоящими Условиями использования. Если не согласны — пожалуйста,
        не используйте Сервис.
      </p>

      <h2>2. Описание Сервиса</h2>
      <p>
        EnergyForge — ИИ-платформа персональной энергетической диагностики.
        На основе ваших ответов на 9 вопросов наш ИИ (Anthropic Claude)
        генерирует персональный 30-дневный план:
      </p>
      <ul>
        <li>Оптимизация сна</li>
        <li>Рекомендации по добавкам</li>
        <li>Управление стрессом</li>
        <li>Рекомендации по питанию</li>
      </ul>

      <h2>3. ⚠️ Медицинская оговорка — ВАЖНО</h2>
      <div className="legal-warning">
        <p>
          <strong>EnergyForge — НЕ медицинский сервис.</strong> Наши
          рекомендации носят{" "}
          <strong>
            исключительно информационный и образовательный характер
          </strong>{" "}
          и не являются медицинской консультацией, диагнозом или лечением.
        </p>
        <ul>
          <li>
            Всегда консультируйтесь с врачом перед изменением диеты, приёмом
            добавок или лекарств для сна.
          </li>
          <li>Не используйте Сервис для диагностики или лечения заболеваний.</li>
          <li>
            Если вы беременны, кормите грудью, имеете заболевания или
            принимаете лекарства — проконсультируйтесь с врачом.
          </li>
          <li>
            В случае медицинской экстренной ситуации — немедленно обратитесь
            в службу скорой помощи.
          </li>
        </ul>
        <p>
          <strong>Мы не несём ответственности</strong> за вред, ущерб или
          негативные последствия от следования рекомендациям Сервиса.
        </p>
      </div>

      <h2>4. Возрастные ограничения</h2>
      <p>
        Вам должно быть <strong>не менее 18 лет</strong> для использования
        Сервиса.
      </p>

      <h2>5. Цены и платежи</h2>
      <p>
        <strong>Тарифы:</strong>
      </p>
      <ul>
        <li>
          <strong>Starter</strong> — Бесплатно (ограниченный функционал)
        </li>
        <li>
          <strong>PRO</strong> — €9.99 разовый платёж
        </li>
        <li>
          <strong>Coach</strong> — €24.99/месяц (ежемесячная подписка)
        </li>
      </ul>
      <p>
        <strong>Условия оплаты:</strong>
      </p>
      <ul>
        <li>Все платежи проводятся через Stripe</li>
        <li>Цены указаны в евро (€) и включают НДС</li>
        <li>
          Подписки (Coach) автоматически продлеваются ежемесячно до отмены
        </li>
        <li>
          Вы можете отменить подписку в любое время в настройках аккаунта
        </li>
      </ul>

      <h2>6. Возврат средств</h2>
      <p>
        <strong>
          Потребители ЕС имеют 14-дневное право отказа
        </strong>{" "}
        согласно Директиве ЕС о правах потребителей:
      </p>
      <ul>
        <li>
          Вы можете запросить возврат в течение 14 дней, если{" "}
          <strong>ещё не получили</strong> доступ к персональному плану.
        </li>
        <li>
          <strong>
            После того, как вы получили доступ к сгенерированному плану,
            право на отказ утрачивается
          </strong>{" "}
          (согласно статье 16(m) законодательства ЕС — цифровой контент,
          предоставленный немедленно после покупки с вашего явного согласия).
        </li>
        <li>
          Для подписки Coach отмена прекращает будущие списания, но не
          возвращает текущий платёжный период.
        </li>
      </ul>
      <p>
        <strong>Для запроса возврата:</strong> напишите на <Mail />.
      </p>

      <h2>7. Обязанности пользователя</h2>
      <p>Вы соглашаетесь:</p>
      <ul>
        <li>Предоставлять точную информацию в анкете</li>
        <li>Использовать Сервис только для личных, некоммерческих целей</li>
        <li>Не передавать, не перепродавать сгенерированные планы</li>
        <li>Не пытаться взломать Сервис</li>
        <li>Не использовать Сервис в незаконных целях</li>
      </ul>

      <h2>8. Интеллектуальная собственность</h2>
      <p>
        Всё содержимое EnergyForge (дизайн сайта, логотип, тексты, графика,
        ИИ-планы) является собственностью EnergyForge и защищено законами об
        авторском праве.
      </p>
      <p>
        Вы получаете{" "}
        <strong>персональную, непередаваемую лицензию</strong> на
        использование вашего плана только для личных целей.
      </p>

      <h2>9. Оговорка об ИИ-контенте</h2>
      <p>
        Планы генерируются ИИ (Anthropic Claude) на основе ваших ответов.
        Хотя мы стремимся к точности:
      </p>
      <ul>
        <li>
          ИИ-рекомендации могут содержать ошибки или устаревшую информацию
        </li>
        <li>Индивидуальные результаты могут значительно отличаться</li>
        <li>Нет гарантии конкретных результатов</li>
        <li>Вы используете рекомендации на свой риск</li>
      </ul>

      <h2>10. Запрещённое использование</h2>
      <p>Запрещено:</p>
      <ul>
        <li>Использовать Сервис, если вам меньше 18 лет</li>
        <li>Выдавать себя за других или предоставлять ложные данные</li>
        <li>Использовать автоматизированные системы (боты)</li>
        <li>Пытаться нарушить работу Сервиса</li>
        <li>Использовать Сервис во вред себе или другим</li>
      </ul>

      <h2>11. Доступность Сервиса</h2>
      <p>
        Мы стремимся обеспечить работу 24/7, но не гарантируем непрерывный
        доступ. Мы можем приостанавливать или изменять Сервис для
        обслуживания.
      </p>

      <h2>12. Ограничение ответственности</h2>
      <p>В максимально допустимом законом объёме:</p>
      <ul>
        <li>EnergyForge не несёт ответственности за косвенные убытки</li>
        <li>
          Наша общая ответственность ограничена суммой, уплаченной за
          последние 12 месяцев
        </li>
        <li>
          Мы не отвечаем за решения, принятые на основе ИИ-рекомендаций
        </li>
      </ul>

      <h2>13. Прекращение</h2>
      <p>
        Мы можем прекратить или приостановить ваш доступ к Сервису в любое
        время за нарушение этих Условий.
      </p>

      <h2>14. Применимое право</h2>
      <p>
        Эти Условия регулируются законодательством Европейского Союза.
      </p>
      <p>
        Споры разрешаются в компетентных судах или через платформу ЕС:{" "}
        <Ext href="https://ec.europa.eu/consumers/odr/">
          https://ec.europa.eu/consumers/odr/
        </Ext>
      </p>

      <h2>15. Изменения Условий</h2>
      <p>
        Мы оставляем за собой право изменять эти Условия в любое время.
        Продолжение использования Сервиса означает согласие с обновлёнными
        Условиями.
      </p>

      <h2>16. Контакты</h2>
      <p>
        По всем вопросам: <Mail />
      </p>
    </>
  );
}
